Handle missed "workdir" argument properly
Before this patch if user simply run "./stateboard.lua" it got:
```
LuajitError: builtin/fio.lua:354: Usage: fio.mktree(path[, mode])
fatal error, exiting the event loop
```

This message could confuse user because it doesn't contain any
useful insformation. This patch adds additional check for case
when "workdir" is omitted.

New error message:
```
LuajitError: "workdir" must be specified
fatal error, exiting the event loop
```

Closes #708